---
type: sharded
default_args: -v --noprealloc --nojournal --smallfiles --nohttpinterface --nssize 6 --quiet
default_version: 2.4
mongoc:
    - name: config1
mongos:
    - name: router1
shards:
    - name: sh1
      type: single
      mongod:
          - name: db1
# vim: ts=4 sts=4 sw=4 et:
